# Generated by Django 4.0.1 on 2022-01-24 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
