# Generated by Django 4.0.1 on 2022-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content',
            field=models.TextField(default='info'),
        ),
    ]
