# Generated by Django 4.0.2 on 2022-02-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
