# Generated by Django 4.0.2 on 2022-02-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
    ]
